---
- name: install packages
  community.general.xbps:
    name: '{{item}}'
  loop:
      # Shell
      - starship # shell prompt
      - fish-shell # powerful shell
      - go # programming language
      - exa # powerful ls
      - bc # maths
      - jq # json processor
      - most # colorized pager
      - bat # colorized cat
      - neovim # futur of vim
      - tree
      - screen # terminal multiplexer
      - asciinema # term recorder
      - expect # automation tool
      - glow # render markdown cli
      - tiny # irc client
      # System
      - xtools # helpers for working with XBPS
      - htop # system monitor
      - net-tools # netstat
      - fwupd # dell firmware updater
      - nmap # port scanner
      - tcpdump # packet analyzer
      - whois # query registry
      - stress # stress test tool
      - efivar # tool to manipulate efi vars
      # Disk
      - iotop # disk "top"
      - ncdu # disk usage analyzer
      # Network
      - nethogs # net "top"
      - openssh
      - sshpass # allow ansible -k
      - sshuttle # vpn through ssh
      - keychain # ssh-agent wrapper
      - wget # downloader
      - bind-utils # dns tools
      - openbsd-netcat # network utility
      - speedtest-cli
      # Utils
      - at # scheduler
      - borg # backup utility
      - borgmatic # backup utility automation
      - gopass # unix password manager
      - pinentry-gtk # gtk gpg pinentry
      - rsync
      - syncthing # sync tool
      - rclone
      - fzf # fuzzy finder
      - neofetch
      - unzip # uncompress zip
      - cifs-utils
      - shellcheck # sh linter
      - pastel # color viewer
      - python-pip # python2 package manager
      - python3-pip # python3 package manager
      - dmidecode # dump dmi table content
      - oath-toolkit # otp tool
      - pastebinit # pastebin wrapper
      - zim # wiki app
#- arch-audit # list vulnerabilities
#- reflector # mirror sorter

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'
