---
- name: install packages
  community.general.xbps:
    name: '{{ item }}'
    loop:
      #      - starship                  # shell prompt
      ##- ttf-impallari-cabin-font # cv font
      ##- ttf-jetbrains-mono       # main font
      #      - noto-fonts-ttf            # unicode font
      #      # Shell
      - fish                      # powerful shell
      #      - exa                       # powerful ls
      #      - bc                        # maths
      #      - jq                        # json processor
      #      - most                      # colorized pager
      #      - bat                       # colorized cat
      #      - neovim                    # futur of vim
      #      - tree                      #
      #      - screen                    # terminal multiplexer
      #      - asciinema                 # term recorder
      #      - expect                    # automation tool
      ##- arch-audit                # list vulnerabilities
      #      # System
      #      - htop                      # system monitor
      #      - net-tools                 # netstat
      ##- reflector                 # mirror sorter
      #      - fwupd                     # dell firmware updater
      #      - nmap                      # port scanner
      #      - tcpdump                   # packet analyzer
      #      - whois                     # query registry
      #      - stress                    # stress test tool
      #      # Disk
      #      - iotop                     # disk "top"
      #      - ncdu                      # disk usage analyzer
      #      # Network
      #      - nethogs                   # net "top"
      #      - openssh                   #
      #      - sshpass                   # allow ansible -k
      #      - wget                      # downloader
      #      - bind-tools                # dns tools
      #      - openbsd-netcat            # network utility
      #      - speedtest-cli             #
      #      # Utils
      #      - borgbackup                # backup utility
      #      - rsync                     #
      #      - rclone                    #
      #      - words                     # dictionnaries
      #      - fzf                       # fuzzy finder
      #      - neofetch                  #
      #      - unzip                     # uncompress zip
      #      - cifs-utils                #
      #      - shellcheck                # sh linter
      #- oath-toolkit              # otp tool
      #- python2-pip               # python2 package manager
      #- python-pip                # python3 package manager
      - dmidecode                 # dump dmi table content
#- python-pre-commit         # pre-commit hook manager
    state: present

- name: Configure root
  user:
    name: root
    shell: '{{shell}}'

- name: Configure user
  user:
    name: '{{user}}'
    shell: '{{shell}}'
