Vagrant.configure("2") do |config|

  config.trigger.before :up, :provision do |trigger|
    trigger.run = {inline: "./download_iso.sh start"}
  end

  config.trigger.after :destroy do |trigger|
    trigger.run = {inline: "./download_iso.sh stop"}
  end

  config.vm.define :voidlinux do |voidlinux|
    voidlinux.vm.hostname = "voidlinux"
    voidlinux.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '2048'
      libvirt.cpus = '1'
      # Create a disk
      libvirt.storage :file,
        size: '50G',
        type: 'qcow2',
        bus: 'sata',
        device: 'sda'
      # Set fr keyboard for vnc connection
      libvirt.keymap = 'fr'
      libvirt.boot 'cdrom'
      libvirt.boot 'hd'
      libvirt.storage :file, :device => :cdrom, :path => '/tmp/hrmpf.iso'
      # Set UEFI boot, comment for legacy
      #libvirt.storage :file, :device => :pflash, :type => 'raw', :path => '/usr/share/qemu/edk2-x86_64-code.fd'
      libvirt.loader = '/usr/share/qemu/edk2-x86_64-code.fd'
    end
  end
end
