repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
    - id: shellcheck
- repo: local
  hooks:
    - id: ansible-syntax-check
      name: Ansible syntax check
      entry: ansible-playbook --syntax-check -i ansible/hosts
      files: ansible/install.yml
      types: [file]
      language: system
