---
- name: copy pre-install zfs snapshot kernel hook
  copy:
    dest: /etc/kernel.d/pre-install/10-zfs
    mode: 0755
    content: |
      #!/bin/sh
      # Create snapshot
      zfs snapshot -r zroot/ROOT@kernel_upgrade_"$(date +%Y-%m-%d_%H:%M:%S)"
      # Prune all except 2 lasts
      for i in $(zfs list -t snapshot | awk '/ROOT@kernel_upgrade/ {print $1}' | head -n -2)
      do
          zfs destroy -r "$i"
      done

- name: copy pre-install vkpurge kernel hook
  copy:
    dest: /etc/kernel.d/pre-install/20-vkpurge
    mode: 0755
    content: |
      #!/bin/sh
      vkpurge rm all

