---
- name: copy pre-install zfs snapshot kernel hook
  copy:
    dest: /etc/kernel.d/pre-install/10-zfs
    mode: 0755
    content: |
      # Find the name of the current boot environment
      BOOTENV="$(awk '$2 == "/" && $3 == "zfs" {print $1}' /proc/mounts)"
      [ -n "${BOOTENV}" ] || exit

      # Create a snapshot of the current state, differntiated by time
      zfs snapshot "${BOOTENV}@kernel_upgrade_$(date +%Y-%m-%d_%H:%M:%S)" || exit

      # Prune all except 2 last kernel_upgrade snapshots
      zfs list -t snapshot -s creation -o name -H "${BOOTENV}" | \
          grep @kernel_upgrade_ | head -n -2 | \
          while read -r snapname; do
              zfs destroy "${snapname}"
          done

- name: copy pre-install vkpurge kernel hook
  copy:
    dest: /etc/kernel.d/pre-install/20-vkpurge
    mode: 0755
    content: |
      #!/bin/sh
      vkpurge rm all

- name: copy pre-install clean_xbps_flatpak kernel hook
  copy:
    dest: /etc/kernel.d/pre-install/30-clean_xbps_flatpak
    mode: 0755
    content: |
      #!/bin/sh
      xbps-remove -Ooy
      flatpak uninstall --unused -y

- name: automatically boot latest lts version
  copy:
    dest: /etc/kernel.d/pre-install/40-boot_latest_lts
    mode: 0755
    content: |
      #!/bin/sh
      kernel_version=$(basename $(xbps-query -f linux$(xbps-query -x linux-lts | grep -Po 'linux\K[0-9.]+') | grep vmlinuz))
      zfs set org.zfsbootmenu:kernel=${kernel_version} zroot/ROOT/voidlinux
