---
- name: install containers packages
  general.community.xbps:
    name: '{{ item }}'
  loop:
    - docker          # high level container runtime
    - docker-compose  # multi-container docker apps
    - podman          # docker alternative without dockerd
    - kubectl         # kubernetes api cli client
    - kubectx         # switch clusters/namespaces
    - kustomize       # yaml templator
    - minikube        # virtualized local kubernetes cluster
    - k9s             # UI to interact with Kubernetes clusters
    - helm            # kubernetes package manager
    - packer          # golden images creator
    - terraform       # infrastructure as code
    # https://github.com/kubernetes-sigs/krew
    - kompose-bin     # docker-compose to manifest convertor
    - k3s-bin         # Lightweight Kubernetes in a signle binary
    - stern           # tail multiple pods on Kubernetes
    - kubespy         # observe Kubernetes resources in real time
    - podman-compose  # mutli-container podman apps

- name: copy subuid files for podman rootless
  template:
    src: subuid.j2
    dest: /etc/subuid

- name: copy subgid files for podman rootless
  template:
    src: subgid.j2
    dest: /etc/subgid

- name: disable zfs overlay storage not supported by podman
  lineinfile:
    path: /etc/containers/storage.conf
    regexp: 'mount_program = "/usr/bin/fuse-overlayfs"'
    line: 'mount_program = "/usr/bin/fuse-overlayfs"'
    state: present

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
