---
- name: install desktop packages
  community.general.xbps:
    name: '{{ item }}'
  loop:
    # DE
    - sway
    - swaybg
    - xorg-server-xwayland
    - Waybar
    - mako # notification daemon
    - kanshi # autorandr for wayland
    - grim # screenshots
    - slurp # region selector
    - wl-clipboard # clipboard manager
    - brightnessctl # brightness manager
    - swayidle
    - xdg-user-dirs
    # Video
    - mesa
    - mesa-demos
    - lib32-virtualgl
    - mesa-vulkan-intel
    - mesa-vulkan-intel-32bit
    - intel-media-driver
    - libva-utils
    # Audio
    - pulseaudio
    - alsa-plugins-pulseaudio
    - pavucontrol
    - pamixer
    - alsa-utils
    # Graphical apps
    - imv # img visualizer
    - kitty # terminal emulator
    - evince # pdf viewer
    - firefox
    - firefox-i18n-fr
    - gimp # img editor
    - kolourpaint # img editor
    - shotwell # photo manager
    - libreoffice-i18n-fr # libreoffice suite fr
    - lxappearance # theme manager
    - mpv # video player
    - Thunar # file manager
    - openvpn
    - playerctl # music player cli controller
    - rdesktop # remote desktop client
    - steam # games manager
    - transmission-gtk # torrent downloader
    - texlive-bin # latex
    - texlive-core # latex
    - texlive-latexextra # latex
    - variety # random backgrounds
    - papirus-icon-theme # icon theme
    - youtube-dl
    # EXAUR
    - wdisplays # arandr for wayland
    - wf-recorder # screen recorder for wayland
    - grimshot # grim+slurp wrapper
    - wofi # rofi for wayland
    - wob # bars for wayland
    - connman-gtk # connman gtk gui
    - gnome-ssh-askpass # ssh askpass gui
    - android-tools # android dir sync
    - font-awesome5
# - x2goclient
# - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
# - equilux-theme
# - downgrade # package downgrader
# - molotov # french tv wrapper
# - swaylock-fancy # locker for wayland
# - google-chrome
# - tiny-irc-client-git
