---
- name: install desktop packages
  community.general.xbps:
    name: '{{item}}'
  loop:
      # DE
      - sway # wayland wm and compositor
      - swaybg # background manager for sway
      - xorg-server-xwayland # xorg backend for wayland
      - Waybar # bar for sway
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - wdisplays # arandr for wayland
      - wf-recorder # screen recorder for wayland
      - grimshot # grim+slurp wrapper
      - wofi # rofi for wayland
      - wob # bars for wayland
      - brightnessctl # brightness manager
      - qt5-wayland # enable qt5 wayland backend
      - libappindicator # tray sway
      - swayidle
      - xdg-user-dirs
      - glfw-wayland
      - pam_rundir # XDG_RUNTIME_DIR when seatd
      # Video
      - mesa # DRI 3D acceleration
      - mesa-dri # DRI 3D acceleration
      - mesa-demos # glxgears command
      - intel-media-driver # intel driver iHD
      - libva-utils # hardware video acceleration
      # Steam
      - mesa-vulkan-intel
      - mesa-vulkan-intel-32bit
      # Audio
      #- pulseaudio # audio server
      - pipewire # audio server
      - alsa-pipewire
      - pavucontrol # pulseaudio ui
      - pulseaudio-utils
      - pamixer # alsa ui
      - alsa-utils # alsa toolbox
      # Graphical apps
      - imv # img visualizer
      - kitty # terminal emulator
      - evince # pdf viewer
      - firefox-i18n-fr # web browser
      - gimp # img editor
      - kolourpaint # img editor
      - shotwell # photo manager
      - swappy # screenshot editor
      - libreoffice # libreoffice
      - libreoffice-i18n-fr # libreoffice suite fr
      - lxappearance # theme manager
      - mpv # video player
      - Thunar # file manager
      - tumbler # thumbnailer
      - openvpn
      - playerctl # music player cli controller
      - rdesktop # remote desktop client
      - steam # games manager
      - transmission-gtk # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - youtube-dl
      - connman-gtk # connman gtk gui
      - gnome-ssh-askpass # ssh askpass gui
      - android-tools # android dir sync
      - Signal-Desktop # messaging app
# - downgrade # package downgrader

- name: configure pam_rundir
  lineinfile:
    path: /etc/pam.d/login
    regexp: 'pam_rundir.so'
    line: 'session		optional	pam_rundir.so'
    state: present

- name: configure pipewire alsa
  file:
    path: /etc/alsa/conf.d
    state: directory
    recurse: yes

- name: symlink pipewire alsa
  file:
    src: '{{ item }}'
    dest: /etc/alsa/conf.d
    state: link
  loop:
    - /usr/share/alsa/alsa.conf.d/50-pipewire.conf
    - /usr/share/alsa/alsa.conf.d/99-pipewire-default.conf
