---
- name: include tasks
  include_tasks:
    file: '{{ item }}.yml'
    apply:
      tags: '{{ item }}'
  tags: always
  loop:
    - desktop
    - pipewire
    - swaylock
    - steam
    - eww
    - runtimedir
