---
- name: install sanoid
  community.general.xbps:
    name: sanoid # zfs snapshot manager

- name: configure sanoid
  copy:
    src: sanoid.conf
    dest: /etc/sanoid

- name: create sanoid lock directory
  file:
    path: /var/run/sanoid
    state: directory

- name: setup sanoid cron snapshot
  ansible.builtin.cron:
    name: "sanoid snapshot"
    minute: "0"
    job: 'flock -n /var/run/sanoid/cron-take.lock -c "TZ=UTC sanoid --take-snapshots"'
    user: root

- name: setup sanoid cron prune
  ansible.builtin.cron:
    name: "sanoid prune"
    minute: "30"
    job: 'flock -n /var/run/sanoid/cron-prune.lock -c "sanoid --prune-snapshots"'
    user: root

- name: setup daily zfs scrub
  copy:
    src: zscrub
    dest: /etc/cron.daily/
    mode: 0755
