---
- name: install zrepl
  community.general.xbps:
    name: zrepl # zfs snapshot manager

- name: configure zrepl
  copy:
    src: zrepl.yml
    dest: /etc/zrepl
  notify:
    - restart zrepl

- name: setup daily zfs scrub
  copy:
    src: zscrub
    dest: /etc/cron.weekly/
    mode: 0755
