---
- hosts: all
  become: yes
  vars:
    user: user
    shell: /usr/bin/fish

  pre_tasks:
    - name: Enable multilib
      community.general.xbps:
        name:
          - void-repo-multilib
          - void-repo-multilib-nonfree

  roles:
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: flatpak, tags: flatpak }
    - { role: appimage, tags: appimage }
    - { role: temp, tags: temp }
    - { role: runit, tags: runit }
    - { role: fonts, tags: fonts }
    - { role: virtualization, tags: virtualization }
    - { role: containers, tags: containers }
