---
- hosts: all
  become: yes

  vars:
    user: user
    shell: /usr/bin/fish

  pre_tasks:

    - name: Enable multilib
      community.general.xbps:
        name:
          - void-repo-multilib
          - void-repo-multilib-nonfree

  roles:
    #    - { role: pacman, tags: pacman }
    #- { role: aur, tags: aur }
    - { role: base, tags: base }
    - { role: desktop, tags: desktop }
    - { role: flatpak, tags: flatpak }
    - { role: appimage, tags: appimage }
    - { role: fonts, tags: fonts }
    #- { role: virtualization, tags: virtualization }
    #- { role: containers, tags: containers }
    #- { role: recovery, tags: recovery }
    #- { role: zfs/systemd-boot-zectl, tags: boot }
    #- { role: zfs/initramfs, tags: boot }
    #- { role: zfs/systemd-scrub-trim, tags: zfs }
