---
- name: install virt packages
  community.general.xbps:
    name: '{{item}}'
  loop:
      - qemu
      - libvirt
      - virt-manager
      - virt-manager-tools
      - dnsmasq
      - vagrant
  notify: restart libvirt

- name: add user to libvirt group
  user:
    name: '{{user}}'
    groups: libvirt
    append: yes

- name: enable nested virtualization
  copy:
    dest: /etc/modprobe.d/kvm.conf
    content: |
      options kvm_intel nested=1

- name: create isos directory
  file:
    path: /var/lib/libvirt/isos
    state: directory

- name: configure isos in libvirt
  shell: virsh pool-create-as --name isos --type dir --target /var/lib/libvirt/isos || true
